### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by mjroeleveld** [randymized/composable-middleware#1]
How do I implement an error handler using composable-middleware?

This simple example doesn't work for me:

```
var express = require('express');
var app = express();
var router = express.Router();
var compose = require('composable-middleware');

router.get('testroute', function(req, res, next) {
  next(new Error('Test error'));
});

function errorHandlers() {
  return compose()
    .use(function(err, req, res, next) {
      console.log('Error handled!');
    });
}

router.use(errorHandlers());
```

**Comment by zhming0** [comment]
According to the [express middleware document](http://expressjs.com/en/guide/using-middleware.html).

> If the current middleware function does not end the request-response cycle, it must call next() to pass control to the next middleware function. Otherwise, the request will be left hanging.

The `errorHandlers` in your example need to at least run `res.send(404)` or something else to end the r-r cycle.
